terraform-google-modules/terraform-google-pubsub

- README.md
- outputs.tf
With this change topic name of output will be compliant with the following format.
```
projects/[PROJECT_ID]/topics/[TOPIC_ID]
```
By this change, it will be more useful for combination with the following resources.
- logging_project_sink
- cloudiot_registry
@aaron-lane @morgante Could you take a look?
> Add ID and URI to module outputs

- README.md
- examples/simple/main.tf
- main.tf
- test/integration/default/controls/pubsub.rb
- test/setup/iam.tf
- variables.tf
> Add message_storage_policy block

- main.tf
The message_retention_duration attribute is supported by the google_pubsub_subscription resource, but it is not yet exposed through this module.
> Add support for message_retention_duration

- README.md
- examples/simple/main.tf
- main.tf
The attribute `expiration_policy` is supported by the
google_pubsub_subscription resource, but has not been exposed in this
module yet. This commit adds support for setting that expiration policy,
defaulting to null if none is given.
> Add support for expiration_policy

- README.md
- main.tf
Following to the comment in the PR: https://github.com/terraform-google-modules/terraform-google-pubsub/pull/22
This PR adds support for the `oidc_token` config used by `google_pubsub_subscription` for push subscriptions.
> feat: Add OIDC token support

- README.md
- examples/cloudiot/main.tf
- examples/kms/main.tf
- examples/simple/main.tf
- main.tf
This PR adds the ability to use `dead_letter_policy`, so when a message can't be acknowledged, pub/sub can forward this message to a dead-letter topic.
> feat: Add support for dead_letter_policy to subscription resources

- main.tf
- test/setup/iam.tf
This PR adds IAM bindings that will grant Pub/Sub permission to publish messages to the dead-letter topic (publisher role), and acknowledge forwarded messages from the subscription(subscriber role).
terraform DOCS ref:
```
The Cloud Pub/Sub service\naccount associated with the enclosing subscription's parent project (i.e., service-{project_number}@gcp-sa-pubsub.iam.gserviceaccount.com) must have permission to Publish() to this topic.
```
> feat: Add iam-bindings to the default pub/sub service account

- Makefile
- README.md
- main.tf
* Add support for retry_policy.maximum_backoff and retry_policy.minimum_backoff
```
module "pubsub" {
source  = "terraform-google-modules/pubsub/google"
version = "~> 1.4"
topic              = "tf-topic"
project_id         = "my-pubsub-project"
push_subscriptions = [
{
name                  = "push"   // required
ack_deadline_seconds  = 20 // optional
push_endpoint         = "https://example.com" // required
x-goog-version        = "v1beta1" // optional
oidc_service_account  = "sa@example.com" // optional
audience              = "example" // optional
expiration_policy     = "1209600s" // optional
dead_letter_topic     = "example-dl-topic" // optional
max_delivery_attempts = 5 // optional
maximum_backoff       = "600s" // optional
minimum_backoff       = "300s" // optional
}
] …
```
> Adding support for retry_policy

- main.tf
- test/setup/iam.tf
This PR adds iam_mmeber_binding which is required when you use `push` with oidc_token block.
`You must grant Pub/Sub the permissions needed to create tokens for your service account. Pub/Sub creates and maintains a special service account for your project: service-PROJECT_NUMBER@gcp-sa-pubsub.iam.gserviceaccount.com. This service account needs the Service Account Token Creator role. If you use the Cloud Console to set up the subscription for push authentication, the role is granted automatically.`
> feat: Add SA token creator binding

- CHANGELOG.md
- README.md
- main.tf
- variables.tf
When you have a push subscription with OIDC enabled, you need to have `roles/iam.serviceAccountTokenCreator` role added to Pub/Sub’s default SA.
But if you would remove one subscription with all its resources it will delete a role as well, but some other subscriptions might still need to use it since there is just one default Pub/Sub service account per project.
This role should be added on the project-factory-module level after you check that the Pub/Sub API is enabled.
> fix: Remove token creator role binding

- docs/upgrading_to_v2.0.md
- main.tf
- outputs.tf
This PR fixes https://github.com/terraform-google-modules/terraform-google-pubsub/issues/66 and fixes #26.
As it has breaking changes, renaming `google_pubsub_subscription` resources in the state file is necessary for preventing destroy/recreate subscriptions:
```
terraform state mv 'google_pubsub_subscription.pull_subscriptions[0]' 'google_pubsub_subscription.pull_subscriptions["subscription1-name"]'
terraform state mv 'google_pubsub_subscription.pull_subscriptions[1]' 'google_pubsub_subscription.pull_subscriptions["subscription2-name"]'
```
> fix: Use subscription names as the keys instead of numeric indexes

- README.md
- main.tf
It is useful to grant permissions for the service account that will subscribe to that pull_subscription just after creating it.
Especially if granting access to the service account from another project.
Also as Kafka-connect needs additional `roles/pubsub.viewer` role for subscribing to the topic, `service_account_viewer_role` switch is provided.
> feat: Grant pull subscription permissions for external service account

- outputs.tf
Since version 4.0.0 of google provider there is no `path` field.
Release: https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.0.0
- pubsub: removed path field from google_pubsub_subscription ([#10424](https://github.com/hashicorp/terraform-provider-google/pull/10424))
Error:
```╷
╷
│ Error: Unsupported attribute
│
│   on outputs.tf line 48, in output "subscription_paths":
│   48:     values({ for k, v in google_pubsub_subscription.push_subscriptions : k => v.path }),
│
│ This object does not have an attribute named "path".
╵
ERRO[0006] 1 error occurred:
* exit status 1
```
> chore: Change output reference

- README.md
- examples/cloudiot/versions.tf
- examples/kms/versions.tf
- examples/simple/versions.tf
- examples/subscriptions_only/versions.tf
- main.tf
- modules/cloudiot/versions.tf
- test/setup/main.tf
- test/setup/versions.tf
- variables.tf
- versions.tf
Already supported on the google_pubsub_topic resource, so just passing through the variable from the tf module terraform-google-pubsub. Argument docs: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_topic#message_retention_duration
Setting the value to null results in no retention policy being set as the default.
Fixes: https://github.com/terraform-google-modules/terraform-google-pubsub/issues/92
> feat!: Add the ability to set the message_retention_duration on a PubSub topic

- examples/cloudiot/main.tf
* `key_algorithm` is read only in hashicorp/tls v4+
> chore: update for compatibilty with hashicorp/tls v4

- README.md
- examples/simple/main.tf
- main.tf
- test/integration/simple/simple_test.go
Hello, this 2 features have been remove from push subscriptions **_enable_message_ordering_** and **_enable_exactly_once_delivery_** they are only available now in pull susbcriptions only. @apeabody
> fix: Add_enable_exactly_once_delivery_on_a_PubSub_subscription

- README.md
- examples/bigquery/README.md
- examples/bigquery/main.tf
- examples/bigquery/outputs.tf
- examples/bigquery/variables.tf
- examples/bigquery/versions.tf
- main.tf
- outputs.tf
- test/setup/iam.tf
- test/setup/main.tf
- variables.tf
- versions.tf
Hi! I wanted to integrate the recently released push to bigquery functionality from google provider 4.32.
I tested as thoroughly as possible on our dev setup, i have to say though i was not able to run the kitchen tests, i can't follow the instructions to the letter give some accounts and privileges constraint that i have. I tried to run it against an already existing project but i was not able to, maybe you can help with that.
Thanks for the consideration, any feedback is highly appreciated
> feat!: :sparkles: added bigquery subcription capability

- main.tf
Additional permissions must be granted to Pub/Sub if a DLT is configured in a subscription as per https://cloud.google.com/pubsub/docs/handling-failures#grant_forwarding_permissions
However if no DLT is configured for the subscription, these resources needn't be created.
closes https://github.com/terraform-google-modules/terraform-google-pubsub/issues/107
> fix: don't grant fwding permissions if no DLT present

- README.md
- main.tf
- variables.tf
Allow disabling project-wide BQ binding creation, which can be useful when the module is used multiple times.
This avoids destroying bigquery bindings for the whole project when a single module instance is destroyed.
> feat: make granting service agent bigquery roles optional

- README.md
- main.tf
Add `enable_message_ordering` for push subscription.
resolved #128
> feat: add enable_message_ordering attribute for push subscription

- README.md
- examples/cloud_storage/main.tf
- main.tf
- test/setup/versions.tf
- versions.tf
I've tried to add support for this new field following https://github.com/GoogleCloudPlatform/magic-modules/pull/10713. However, I'm having some trouble with having the example in `examples/cloud_storage` pick up the new filename_datetime_format field (it seems to be ignored).
With the updated example which attempts to set filename_prefix, filename_suffix, and filename_datetime_format, I get this with `terraform plan`:
```sh
terraform-google-pubsub/examples/cloud_storage$ terraform init -upgrade
Initializing the backend...
Upgrading modules...
Downloading registry.terraform.io/terraform-google-modules/pubsub/google 6.0.0 for pubsub...
- pubsub in .terraform/modules/pubsub
Initializing provider plugins...
- Finding hashicorp/google versions matching ">= 4.78.0, < 6.0.0"...
- Finding latest …
```
> feat(TPG>=5.31)!: add cloud storage filename datetime format support

- metadata.yaml
Generate output type metadata for `subscription_names`,  `subscription_paths` and `topic_labels`
For `subscription_names`,  and `subscription_paths`  autogeneration gave a tuple:
```
type:
- tuple
- - string
- string
- string
- string
```
Where the number of strings depended on the number of subscriptions I specified in my  terraform.tfvars:
```
...
pull_subscriptions = [
{
name                 = "pull"
ack_deadline_seconds = 10
},
{
name                 = "pull2"
ack_deadline_seconds = 10
},
{
name                 = "pull3"
ack_deadline_seconds = 10
},
{
name                 = "pull4"
ack_deadline_seconds = 10
},
]
```
I generated the output type metadata using on 1 subscription
> chore: generate remaining output type metadata

- README.md
- main.tf
- metadata.display.yaml
- metadata.yaml
- variables.tf
The storage binding is needed for creating GCS subscription.
Although this change can be useful when the module is used multiple times.
This avoids destroying storage bindings for the whole project when a single module instance is destroyed.
> feat: Add conditional storage iam binding

- metadata.display.yaml
How the regex works ?
1.  `[a-fh-zA-Z][a-zA-Z0-9\-._~%+]{0,254}`: Matches if the string starts with any letter except g, followed by 0 to 254 allowed characters (`a-zA-Z0-9\-._~%+`).
2.  `g(...)`: Matches if the string starts with g, and the rest of the string matches one of the nested alternatives:
* `$`: The string is exactly `"g"`.
* `[^o][a-zA-Z0-9\-._~%+]{0,253}`: The second character is not o, followed by 0 to 253 allowed characters.
* `o(...)`: The second character is o (starts `"go"`), and the rest matches:
* `$`: The string is exactly `"go"`.
* `[^o][a-zA-Z0-9\-._~%+]{0,252}`: The third character is **not 'o'**, followed by 0 to 252 allowed characters.
* `o(...)`: The third character **is 'o'** (starts `"goo"`), and the rest matches:
* `$`: The string is exactly `"goo"`.
* …
> fix: fixed topic regex to make it compatible with golang re2

- Makefile
- metadata.yaml
- test/setup/iam.tf
- test/setup/main.tf
Introduced:
- per_module_roles: to config required roles to run each sub modules.
- per_module_service: to config required services to run each sub modules.
Added feature flag `--per-module-requirements` to generate_docs cmd, to align with the per module configs.
> feat: per module requirements configs for pubsub
